### ISSUE TITLE
Allow tree reconstruction (in compare.py) from arbitrary command line script?

### ISSUE THREAD

**Issue by Anaphory** [Anaphory/simuling#16]
Should we permit passing any external program to `compare.py`, with the assumption that that program takes one filename containing a word list and produces one line of output containing one tree in Newick format?

This might allow us to extend the program's behaviour very easily.

**Comment by LinguList** [comment]
yep, seems to be very useful, and will probably also be more transparent or tidy.

**Comment by Anaphory** [comment]
`compare.py` is obsolete. The new recommended way to use simuling is through many small purpose applets.
