### ISSUE TITLE
Sort out the file format

### ISSUE THREAD

**Issue by Anaphory** [Anaphory/simuling#17]
Even with current LingPy, I think it is possible to work out a format that can work with Beastling and LingPy. This would be useful, because then we could run more different analysis tools on the simulation data.

Currently, the simulation generates `tsv` files with header

    ID DOCULECT CONCEPT IPA COGID

In principle – actually, there is some “noise”

    # Wordlist
    
    # DATA

before that.

I suggest making sure that `phylo` generates valid CLDF, with columns

    ID Language_ID Feature_ID Value Global_CogID Concept_CogID

where `Feature_ID` is the concept, `Value` is a dummy column reserved for future extensions that actually implement word forms with sound changes (or something like that), `Global_CogID` is the current `IPA`, containing the same value for all cognate words, and `Concept_CogID` is the current `COGID`, ie. a re-numeration of `(Feature_ID, Global_CogID)`.

The reconstruction methods in `compare.py` must then be made aware of the new default column names.

**Comment by LinguList** [comment]
I'll take care of this: just give me transparent headers in the column,
and a transparent separator. There's the function wordlist.read_csv('')
or similar in lingpy, which works for this. I'll make sure it works from
lingpy's side.

**Comment by Anaphory** [comment]
With the weights, the header will be

    ID Language_ID Feature_ID Value Weights Global_CogID Concept_CogID

**Comment by LinguList** [comment]
Allright!

**Comment by Anaphory** [comment]
Example: (The Value column is empty, as suggested above.)

```
head simulation-1.tsv
==> simulation-1.tsv <==
ID	Language_ID	Feature_ID	Value	Weight	Global_CogID	Concept_CogID
0	C	6229		1	1332	0
0	C	6499		7	1721	1
0	C	6448		7	389	2
0	C	6070		1	1325	3
0	C	8169		1	42	4
0	C	6248		2	1362	5
0	C	6464		2	1727	6
0	C	7574		1	828	7
0	C	6541		1	1321	8

**Comment by LinguList** [comment]
Quick point: the ID should be unique, and not zero. and ideally, the Concept_CogID should also be larger than zero, as zero is often defined to indicate empty fields.

**Comment by Anaphory** [comment]
Oh, good! The first is a bug, there's an `i+=1` missing. (And some tests to avoid this in the future.)
The second one is a new specification, I'll change it. (I have actually thought of how to change it before, so it's just a matter of putting that implementation in place.)

**Comment by Anaphory** [comment]
```
$ head simulation-0.tsv 
ID	Language_ID	Feature_ID	Value	Weight	Global_CogID	Concept_CogID
1	A	1830		1	19	1
2	A	1394		1	1389	2
3	A	2400		1	655	3
4	A	914		5	1295	4
5	A	18		1	1880	5
6	A	455		1	1184	6
7	A	81		1	468	7
8	A	1349		1	979	8
9	A	3659		1	476	9

**Comment by Anaphory** [comment]
```
$ head simulation-0.tsv 
ID	Language_ID	Feature_ID	Value	Weight	Global_CogID	Concept_CogID
1	A	1830		1	19	1
2	A	1394		1	1389	2
3	A	2400		1	655	3
4	A	914		5	1295	4
5	A	18		1	1880	5
6	A	455		1	1184	6
7	A	81		1	468	7
8	A	1349		1	979	8
9	A	3659		1	476	9

**Comment by LinguList** [comment]
excellent!
