### ISSUE TITLE
How to feed root lists to reconstructor?

### ISSUE THREAD

**Issue by Anaphory** [Anaphory/simuling#18]
Currently, the `-r` simulation output (“List of all roots/reflexes”) generates a word list similar in format to the “Basic vocabulary” (`-b B`) sampler. For each language sampled, `-r`'s word list contains the most weighted meaning for any and all reflexes found in the language.

The reconstruction methods are currently agnostic of this semantic difference in word list construction, and I am not sure how to change this to something reasonable.

**Comment by LinguList** [comment]
if one wants to feed ALL form-meaning pairs, this is possible, but an additional field should be added, containing a "RANK", so a field RANK, following the order of frequency (I suppose: integers). With the rank, one can easily exclude words from lingpy's calculations (be it in a principled way or by tweaking the data).

**Comment by LinguList** [comment]
we discussed this also as a feature in cldf, where people brought up the idea that synonyms may be ranked according to frequency.

**Comment by Anaphory** [comment]
The issue is not that (we could just store the weight of the word-concept connection), it's that the `-b` lists should be evaluated by “Which cognate class is present in this meaning slot”, the `-r` lists should be evaluated by “Which cognate classes have reflexes in this language”, but that's not information that is available trivially from the content of the word list.

At least, that's what I think you want to do with these two different sampling methods?

**Comment by LinguList** [comment]
Okay, I don't really understand. If you have a cross-semantic cognate encoding, what we have, since a unique ID (an integer, the same which reads into the field "ipa"), is a cross-semantic cognate coding, which is formally identical with an etymological dictionary and automatically representable as both a collection of meaning-restricted cognate sets (paps, where the unique ID is given the concept ID to further distinguish it), or as a pure cross-semantic etymological dictionary. these two things are thus automatically covered, no matter which coding, as long as ids stay unique across concept slots (so arm and hand may get the same ID, indicating cross-semantic cognacy). Or did you mean something else?

**Comment by Anaphory** [comment]
Ah! That is effectively building *two reconstruction methods* from *one word list sample method*, one taking cross-smantic cognate classes, and one taking within-semantic cognate classes.

I thought you had called for *two sample methods*, one going “Here is a list of concepts, how do you express them in your language?” and one going “Here is a list of roots/cognate sets, can you think of a word, any word, even if it's really obscure, that uses this root? I only need the first such word you can think of.” (The first is what `-b` does, the second what `-r` does.)

**Comment by LinguList** [comment]
sorry, no, I was obviously not really making it explicit enough, it is just that he "wordlist.get_etymdict()", which comes from STARLING is so deeply ingrained in my head that I forget to be careful when talking about it, what I actually mean. But we should add some ranks, or allow to add synonymy up to a percentage cutoff or the like, what do you think?

**Comment by Anaphory** [comment]
I'm happy to output the weight=cognitive activation for every word, if you think that's helpful, or do something else if you have a better idea.

What will you want to do with that?

**Comment by LinguList** [comment]
I was thinking like this: in natural word lists we often have a number of synonyms, often even up to 5, etc., depending on data quality and screening. If we allow for synonymy, ranked by frequency, we can check for different accounts, like synonymy <= 4, <=3, etc., and see how much this may impact on quality of results. I'm thinking like this:

* a concept has n forms which expressit, each one weighted
* the proportion of a form expressing is the division of the weight of the form by the sum of all weights
* if we define a cutoff, like: 0.5 and higher as proportion, or 0.25 and higher than proportion, we could easily create lists in which concepts have different rates of synonymity

This would come quite close to a synonym distribution as we expect it in normal languages. But by passing the frequencies (the proportion scores, I mean), we can even further test to which degree the concept frequency impacts on finding the right phylogeny.

**Comment by Anaphory** [comment]
That's pretty much what the weights currently do. I'll make sure you get them, once I fix some other issue coming from me trying to provide a way to specify a colexification graph to the simulation, as basis for semantic shift.

**Comment by LinguList** [comment]
Ah, that's why you looked into the clics-graph? Unfortunetely, the pyclics is not yet really workable, unless for my analyses, and I'm currently exploring them, but you can use the analyses which have been computed, like the gml files (using the methods adjusting for unicode in gml).

**Comment by Anaphory** [comment]
Yep. With the next pull request, phylo can take an argument specifying any GML file and uses that for the concept set. (I got the clics graph working, those 5 issues I found were everything necessary there.)
