### ISSUE TITLE
Better tree support

### ISSUE THREAD

**Issue by Anaphory** [Anaphory/simuling#22]
Currently, the basic phylogenetic trees are generated by Lingpy's Random Tree algorithm. We might want to feed specific trees into the simulation.

The current trees have branches of roughly even length. We might want to support trees with varying branch lengths, which probably also means that instead of `--min` and `--max`, we would have a factor translating branch lengths into number of changes. This would lose us some randomness for the default model, but that should not matter much.

**Comment by LinguList** [comment]
good idea! There is a parameter for branch length in the random trees
that could be tweaked.

**Comment by LinguList** [comment]
if this is not satisfying enough, porting and modifying the method from
lingpy may be even better, and it would resolve lingpy as a dependency
for tree creation.

**Comment by Anaphory** [comment]
Well, step 1: Reduplicate current behaviour.

I might have a look whether the `newick` package has anything of use.

**Comment by Anaphory** [comment]
Basic support is now in, see #23
