### ISSUE TITLE
Enforce low synonymy and low semantic spread

### ISSUE THREAD

**Issue by Anaphory** [Anaphory/simuling#25]
Currently, our `Language` objects have no reason to develop realistic vocabularies. We should at some point consider whether and how we want to enforce the following real-life observations.

 - [ ] Meanings should not be connected to many words
 - [ ] Words should not be connected to many weakly connected or unconnected meanings

**Comment by LinguList** [comment]
sorry for late reply:

by meanings connect to many words, you mean, a meaning should not have TOO many words or more than one word? I guess, in terms of synonymy observed in languages, many words per meaning is totally fine, but of course not TOO many, although our model should handle this with the weights (the meaning "head", for example, can also be expressed by other words than "head", although "head" has the largest potential).

So this should be more like a parameter which we can tune, not a thing that should be fixed, as I assume that in principle, there is some average (or say a maximum) rate of synonymity across languages, but this is also related for frequency of word usage in living languages.

**Comment by Anaphory** [comment]
I do mean “Many” as opposed to “Few”, indeed. (Not “Many” as opposed to “One”.)
I am just looking at what our evolutionary model does along a loooong branch, to see how much this is an issue.

**Comment by Anaphory** [comment]
It *does* show strange behaviour. I just evolved a single branch down some million of time steps, and with default values I end up with only quite new words, all of weight 1.

I added some code to `gain` saying “If word 1 gains weight on meaning A, reduce the weight of some other word meaning A”, and I get one word meaning **everything**, with weights in the 200s, and a few very new words on some concepts, like 62 in the run below.

    11161	A	grass-skirt		1	20360	3232
    11162	A	frog		194	62	2857
    11163	A	horn		276	62	2541
    11164	A	banyan		1	52013	4612
    11165	A	miss (target)		137	62	2858
    11166	A	touch		594	62	2859
    11167	A	older brother		239	62	2860
    11168	A	warm		103	62	2861
    11169	A	cockroach		152	62	2862
    11170	A	chili pepper		51	62	2863
    11171	A	cooked		263	62	2864
    11172	A	woods, forest		206	62	2865

**Comment by LinguList** [comment]
Strange. Unfortunately, I have no clear idea at the moment, why this
could happen...

**Comment by Anaphory** [comment]
Well, it is not unexpected for a kind-of evolutionary game theory model (in the wider sense), that either one allele fixates or something new comes about time and time again.

However, the confusing bit is that either we get very low weights for those new things or very high weights for the fixated alleles. We had set the probabilities to average weight changes of 0, so it's strange that they don't stay roughly even.

**Comment by Anaphory** [comment]
I have just created a system that *might* do this, by using a naming game approach (not very elaborate, with a few choices that need to be discussed at some point). Pull request is coming through, and then it's testing what that system actually does.

**Comment by Anaphory** [comment]
The naming game seems to do this reasonably enough, so I guess it's time to close this issue.
